name: release
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target:
              - x86_64-unknown-linux-gnu
              - x86_64-apple-darwin
              - aarch64-apple-darwin
            extensions: tar.gz tar.gz.sha256
    steps:
      - uses: actions/checkout@v3
      - name: Setup Fluent CI
        uses: fluentci-io/setup-fluentci@v1
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build
        run: fluentci run . compile
        env:
          TAG: ${{ env.RELEASE_VERSION }}
          TARGET: ${{ matrix.target }}
      - name: Upload release assets
        run: fluentci run github_pipeline release_upload
        env:
          TAG: ${{ env.RELEASE_VERSION }}
          FILE: /assets/fluentci_${{ env.RELEASE_VERSION }}_${{ matrix.target }}.${{ matrix.extensions }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
